# Transcode japanese_rules.cc double-array tables into a C# source file.
# char[] tables are all \xHH escapes -> byte[]; DoubleArray[] {base,check} -> (short,ushort)[].
import re

SRC = r"C:\Users\IMT\dev\Illumoz\src\base\strings\internal\japanese_rules.cc"
OUT = r"C:\Users\IMT\dev\Illumoz\src_net\Mozc.Base\JapaneseRules.cs"

text = open(SRC, encoding="utf-8", errors="surrogateescape").read()

tables = {}
for m in re.finditer(r'const char (\w+)\[\] =\s*(.*?);', text, re.S):
    name, body = m.group(1), m.group(2)
    tables[name] = [int(h, 16) for h in re.findall(r'\\x([0-9A-Fa-f]{2})', body)]

arrays = {}
for m in re.finditer(r'const DoubleArray (\w+)\[\] = \{(.*?)\};', text, re.S):
    name, body = m.group(1), m.group(2)
    pairs = re.findall(r'\{\s*(-?\d+)\s*,\s*(-?\d+)\s*\}', body)
    arrays[name] = [(int(a), int(b)) for a, b in pairs]

out = []
out.append("// Auto-generated by tools/transcode_japanese_rules.py from")
out.append("// src/base/strings/internal/japanese_rules.cc. Do not edit by hand.")
out.append("namespace Mozc.Base;")
out.append("")
out.append("internal static class JapaneseRules")
out.append("{")
for name, bs in tables.items():
    out.append(f"    internal static readonly byte[] {name} = new byte[] {{{','.join(map(str, bs))}}};")
for name, ps in arrays.items():
    body = ",".join(f"({a},{b})" for a, b in ps)
    out.append(f"    internal static readonly (short Base, ushort Check)[] {name} = new (short, ushort)[] {{{body}}};")
out.append("}")

open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"tables={len(tables)} arrays={len(arrays)}")
